### ISSUE TITLE
Fortune Teller App 

### ISSUE THREAD

**Issue by cernelkm** [WCCI-PartTime/Course-Resources#1]
# Fortune Teller
## Overview
Develop a console application that will tell the user�s fortune based on data received from the user.
[Example](https://drive.google.com/file/d/0B5A2Jb7LrKtqemNfd2xsUFk5Y28/view)

### Part 1
- [ ] Ask the user for the user�s first name
- [ ] Ask the user for the user�s last name
- [ ] Ask the user for the user�s age
- [ ] Ask the user for the user�s birth month
- [ ] Ask the user for the user�s favorite ROYGBIV color
  - [ ] If the user does not know what ROYGBIV is, ask them to enter �Help� (print with the quotation marks) to get a list of the ROYGBIV colors
- [ ] Ask the user for the number of siblings the user has

### Part 2
- [ ] If the user�s age is an odd number, then they will retire in ____ years, or ___ years if their age is an even number.
- [ ] If the user�s number of siblings is 0, then they will live in ___(location), or 1 then they will live in ___(location), or 2 then they will live in ___ (location), or 3 then they will live in ___ (location), or more than 3 then they will live in ____ (location).
- [ ] Depending on which ROYGBIV color is the user�s favorite, they will have a specific mode of transportation (i.e. car, boat, plane, etc.) 
- [ ] If the first letter of the user�s birth month can be found in either their first or last name, then they will have $____ in the bank, or if the second letter of the user�s birth month can be found in either the user�s first or last name, then they will have $____ in the bank, or if the third letter of the user�s birth month can be found in either the user�s first or last name, then they will have $____ in the bank. If there are no common letters, then they will have $____ in the bank.

### Part 3
- [ ] The user�s fortune should be written as such:
  - [ ] [First Name] [Last Name] will retire in [# of Years] with [Amount of Money] in the bank, a vacation home in [Location] and a [Mode of Transportation].
- [ ] After telling the user�s fortune, ask the user if they would like to try again. If they would then the program should start over, otherwise the program should end.
- [ ] Program should be able to handle whether or not a user inputs capital or lowercase letters.

### Optional Extension Challenge:
- [ ] Give the user the ability to quit the program at any point where the program is looking for user input, by typing �Quit� (should not be case sensitive). The program should print �Nobody likes a quitter...� before ending.
- [ ] Give the user the ability to restart the program at any point where the program is looking for user input by typing �Restart� (should not be case sensitive).

### Project Submission
[GitHub Submission Link](https://docs.google.com/a/wecancodeit.org/forms/d/1My9F-7TyvtTYCszGgFv1NKcQ74cB20hOWJ_tHYMo03s/viewform)
